services:
  booking_backend_service:
    container_name: 'booking_backend'
    build:
      context: .
#    ports:
#      - "7878:8000"
    networks:
      - momoa-network
    env_file:
      - .env

  booking_celery_worker_service:
    container_name: 'booking_celery_worker'
    build:
      context: .
    networks:
      - momoa-network
    env_file:
      - .env
    command: "celery --app=src.tasks.celery_app:celery_instance worker -l INFO"

  booking_celery_beat_service:
    container_name: 'booking_celery_beat'
    build:
      context: .
    networks:
      - momoa-network
    env_file:
      - .env
    command: "celery --app=src.tasks.celery_app:celery_instance beat -l INFO"

networks:
  momoa-network:
    external: true
